const easyTravelWords = [
    { word: "airport", sentence: "We arrived at the airport two hours early.", definition: "A place where airplanes take off and land." },
    { word: "ticket", sentence: "She bought a plane ticket to Paris.", definition: "A document that allows you to travel or enter a place." },
    { word: "luggage", sentence: "His luggage was too heavy for the flight.", definition: "Bags and suitcases used for traveling." },
    { word: "passport", sentence: "Don't forget your passport before going to the airport.", definition: "An official document needed to travel to other countries." },
    { word: "hotel", sentence: "They stayed at a hotel near the beach.", definition: "A place where people pay to sleep and stay temporarily." },
    { word: "map", sentence: "He used a map to find the museum.", definition: "A drawing that shows the locations of places." },
    { word: "guide", sentence: "The guide showed us around the city.", definition: "A person or book that gives information about a place." },
    { word: "bus", sentence: "We took a bus from the airport to the hotel.", definition: "A large vehicle that carries many passengers." },
    { word: "train", sentence: "The train left the station at 9 AM.", definition: "A vehicle that moves on tracks and carries people or goods." },
    { word: "plane", sentence: "The plane flew above the clouds.", definition: "A flying vehicle with wings and engines." },
    { word: "car", sentence: "They rented a car to explore the countryside.", definition: "A road vehicle used to carry passengers." },
    { word: "trip", sentence: "We went on a trip to the mountains.", definition: "A journey to a place and back again." },
    { word: "tour", sentence: "We took a boat tour of the island.", definition: "A visit around a place for enjoyment or learning." },
    { word: "beach", sentence: "The beach was sunny and warm.", definition: "A sandy area next to the sea or ocean." },
    { word: "sun", sentence: "The sun was shining brightly on the coast.", definition: "The star that gives light and heat to the earth." },
    { word: "bag", sentence: "She packed her bag with clothes and snacks.", definition: "A container used to carry things." },
    { word: "stay", sentence: "We will stay at a cabin in the forest.", definition: "To live or remain in a place for a time." },
    { word: "flight", sentence: "Their flight was delayed due to weather.", definition: "A journey by air in an airplane." },
    { word: "photo", sentence: "He took a photo of the waterfall.", definition: "A picture made with a camera." },
    { word: "view", sentence: "The view from the mountain was amazing.", definition: "What you can see from a certain place." },
    { word: "visit", sentence: "We plan to visit a museum today.", definition: "To go to see a person or place." },
    { word: "rest", sentence: "We took a short rest at the park.", definition: "To relax or take a break." },
    { word: "snack", sentence: "She brought a snack for the train ride.", definition: "A small amount of food eaten between meals." },
    { word: "water", sentence: "Always carry water when you travel.", definition: "A clear liquid that people need to drink." },
    { word: "food", sentence: "We tried the local food at the market.", definition: "Something people eat to live." },
    { word: "room", sentence: "Our hotel room had a great view.", definition: "A part of a building enclosed by walls." },
    { word: "key", sentence: "She lost the key to her room.", definition: "A small object used to open or lock things." },
    { word: "ticket", sentence: "He showed the ticket to board the train.", definition: "Proof that you have paid for a service or event." },
    { word: "ride", sentence: "The ride to the airport took 30 minutes.", definition: "A journey in a vehicle." },
    { word: "plan", sentence: "We made a plan for our weekend trip.", definition: "An idea or method for doing something." }
  ];
  
  export default easyTravelWords;
  