const easyGeneralWords = [
  { word: "apple", sentence: "She ate an apple for breakfast.", definition: "A round fruit with red, green, or yellow skin and a sweet taste." },
  { word: "ball", sentence: "He kicked the ball to his friend.", definition: "A round object used in various sports and games." },
  { word: "cat", sentence: "The cat sat on the windowsill.", definition: "A small domesticated carnivorous mammal with soft fur." },
  { word: "dog", sentence: "The dog barked loudly at the stranger.", definition: "A domesticated carnivorous mammal, often kept as a pet." },
  { word: "elephant", sentence: "The elephant is the largest land animal.", definition: "A large mammal with a trunk, native to Asia and Africa." },
  { word: "flower", sentence: "She picked a flower from the garden.", definition: "A colorful, fragrant part of a plant that produces seeds." },
  { word: "green", sentence: "The grass is green and fresh.", definition: "A color between blue and yellow on the spectrum." },
  { word: "house", sentence: "They live in a small house near the beach.", definition: "A building for human habitation." },
  { word: "island", sentence: "We vacationed on a beautiful island.", definition: "A piece of land surrounded by water." },
  { word: "juice", sentence: "He drank a glass of orange juice.", definition: "A liquid extracted from fruits or vegetables." },
  { word: "king", sentence: "The king ruled over the kingdom.", definition: "A male ruler of a country or territory." },
  { word: "lamp", sentence: "The lamp lit up the room.", definition: "A device for producing light." },
  { word: "moon", sentence: "The moon was bright in the night sky.", definition: "The natural satellite of the Earth." },
  { word: "night", sentence: "We stayed up all night talking.", definition: "The period of darkness between sunset and sunrise." },
  { word: "orange", sentence: "She ate an orange as a snack.", definition: "A citrus fruit with a tough skin and a sweet, tangy taste." },
  { word: "pen", sentence: "She wrote a letter with a blue pen.", definition: "A small writing instrument with ink." },
  { word: "queen", sentence: "The queen greeted her people with a smile.", definition: "A female ruler of a country or territory." },
  { word: "rain", sentence: "It started to rain heavily in the afternoon.", definition: "Water that falls from the sky in droplets." },
  { word: "sun", sentence: "The sun was shining brightly.", definition: "The star at the center of our solar system." },
  { word: "tree", sentence: "The tree had many branches and leaves.", definition: "A large plant with a trunk and branches." },
  { word: "umbrella", sentence: "She opened the umbrella to shield herself from the rain.", definition: "A device used for protection against rain." },
  { word: "vase", sentence: "She placed the flowers in a beautiful vase.", definition: "A container used to hold flowers." },
  { word: "window", sentence: "The window was open, letting in the fresh air.", definition: "An opening in a wall or door to let in light and air." },
  { word: "climate", sentence: "The climate in this region is very hot.", definition: "The weather conditions in an area over a long period." },
  { word: "yellow", sentence: "The sunflower is bright yellow.", definition: "A color like that of ripe lemons or the sun." },
  { word: "zebra", sentence: "The zebra had black and white stripes.", definition: "An African wild horse with black-and-white stripes." },
  { word: "balloon", sentence: "She released the balloon into the sky.", definition: "A flexible bag filled with air or gas." },
  { word: "cloud", sentence: "The cloud was white and fluffy in the sky.", definition: "A visible mass of condensed water vapor in the sky." },
  { word: "fire", sentence: "They built a campfire to keep warm.", definition: "A process of combustion that produces heat and light." },
  { word: "guitar", sentence: "He played a song on his guitar.", definition: "A stringed musical instrument played by strumming or plucking." }
];

export default easyGeneralWords;
