const hardGeneralWords = [
    { word: "abandon", sentence: "The ship was abandoned in the storm.", definition: "To leave behind or give up on something or someone." },
    { word: "benevolent", sentence: "Her benevolent actions helped many in need.", definition: "Showing kindness and goodwill." },
    { word: "camaraderie", sentence: "There was a strong sense of camaraderie in the team.", definition: "Mutual trust and friendship among people who spend a lot of time together." },
    { word: "detrimental", sentence: "Smoking is detrimental to your health.", definition: "Causing harm or damage." },
    { word: "emphatic", sentence: "He gave an emphatic answer to the question.", definition: "Expressing something forcibly and clearly." },
    { word: "facetious", sentence: "His facetious comment was misunderstood as serious.", definition: "Treating serious issues with deliberately inappropriate humor." },
    { word: "gregarious", sentence: "She was a gregarious person who loved being around others.", definition: "Fond of company; sociable." },
    { word: "hierarchy", sentence: "The company's hierarchy is quite complex.", definition: "A system in which people or things are arranged according to rank or importance." },
    { word: "inconspicuous", sentence: "The thief wore inconspicuous clothes to blend in.", definition: "Not noticeable or attracting attention." },
    { word: "juxtapose", sentence: "The photographer loved to juxtapose light and dark elements in his pictures.", definition: "To place things side by side for comparison." },
    { word: "lament", sentence: "He lamented the loss of his childhood home.", definition: "To express grief or sorrow." },
    { word: "meticulous", sentence: "She was meticulous about her work, checking every detail.", definition: "Showing great attention to detail; very careful and precise." },
    { word: "nefarious", sentence: "The villain had a nefarious plan to take over the city.", definition: "Wicked or criminal." },
    { word: "obfuscate", sentence: "The politician tried to obfuscate the issue during the debate.", definition: "To make something unclear or unintelligible." },
    { word: "pragmatic", sentence: "She took a pragmatic approach to solving the problem.", definition: "Dealing with things sensibly and realistically." },
    { word: "quintessential", sentence: "He was the quintessential gentleman.", definition: "Representing the most perfect or typical example of a quality or class." },
    { word: "resilient", sentence: "After the storm, the community showed how resilient they were.", definition: "Able to withstand or recover quickly from difficult conditions." },
    { word: "sophisticated", sentence: "The watch was a sophisticated piece of technology.", definition: "Highly developed or refined." },
    { word: "tangible", sentence: "There was a tangible sense of relief after the announcement.", definition: "Perceptible by touch; capable of being touched or felt." },
    { word: "ubiquitous", sentence: "Smartphones are ubiquitous in modern society.", definition: "Present, appearing, or found everywhere." },
    { word: "vulnerable", sentence: "The elderly are particularly vulnerable during the winter months.", definition: "Susceptible to physical or emotional harm." },
    { word: "whimsical", sentence: "The whimsical painting brightened the room.", definition: "Playfully quaint or fanciful, especially in an appealing and amusing way." },
    { word: "xenophobic", sentence: "His xenophobic views made it difficult for him to trust people from other countries.", definition: "Having or showing a dislike of or prejudice against people from other countries." },
    { word: "yearn", sentence: "She yearned for the days when life was simpler.", definition: "To have an intense feeling of longing or desire for something." },
    { word: "zealous", sentence: "He was a zealous supporter of the new policy.", definition: "Having or showing great energy or enthusiasm in pursuit of a cause or objective." },
    { word: "ephemeral", sentence: "The beauty of the sunset was ephemeral, lasting only a few minutes.", definition: "Lasting for a very short time." },
    { word: "fortuitous", sentence: "It was a fortuitous meeting that led to the big opportunity.", definition: "Happening by chance, often in a lucky or fortunate way." },
    { word: "immutable", sentence: "The laws of physics are immutable, not changing over time.", definition: "Unchanging over time or unable to be changed." },
    { word: "nonchalant", sentence: "He gave a nonchalant shrug when asked about his future plans.", definition: "Appearing casually calm and relaxed; not displaying anxiety, interest, or enthusiasm." },
    { word: "ubiquitous", sentence: "Wi-Fi has become ubiquitous in public spaces.", definition: "Present or found everywhere." }
  ];
  
export default hardGeneralWords;
