const mediumGeneralWords = [
  { word: "genuine", sentence: "She has a genuine smile." },
  { word: "accommodate", sentence: "The hotel can accommodate up to 100 guests." },
  { word: "conscience", sentence: "His conscience wouldn't let him lie." },
  { word: "embarrass", sentence: "I didn’t want to embarrass him in front of everyone." },
  { word: "maintenance", sentence: "The car needs regular maintenance." },
  { word: "occurrence", sentence: "It was a rare occurrence." },
  { word: "recommend", sentence: "Can you recommend a good book?" },
  { word: "rhythm", sentence: "The music had a catchy rhythm." },
  { word: "separate", sentence: "We sleep in separate rooms." },
  { word: "threshold", sentence: "She stood at the threshold of the room." },
  { word: "vacuum", sentence: "Use the vacuum to clean the floor." },
  { word: "weird", sentence: "That movie was really weird." },
  { word: "commitment", sentence: "She made a commitment to exercise daily." },
  { word: "discipline", sentence: "He needs more discipline to study effectively." },
  { word: "existence", sentence: "The existence of life on other planets is unknown." },
  { word: "harass", sentence: "They were warned not to harass their classmates." },
  { word: "independent", sentence: "She became independent after moving out." },
  { word: "judgment", sentence: "He used good judgment during the crisis." },
  { word: "knowledge", sentence: "Reading increases your knowledge." },
  { word: "liaison", sentence: "She acted as a liaison between the teams." },
  { word: "millennium", sentence: "The year 2000 marked a new millennium." },
  { word: "noticeable", sentence: "The stain was very noticeable." },
  { word: "occasionally", sentence: "We occasionally go out for dinner." },
  { word: "privilege", sentence: "It's a privilege to be here." },
  { word: "questionnaire", sentence: "Please fill out the questionnaire." },
  { word: "receive", sentence: "Did you receive the email?" },
  { word: "schedule", sentence: "What's your schedule for today?" },
  { word: "technique", sentence: "She has great painting technique." },
  { word: "unforeseen", sentence: "The trip was delayed by unforeseen circumstances." },
  { word: "visible", sentence: "The moon was clearly visible." }
];

export default mediumGeneralWords;
